# Redirect rules for michelleandkeaton.com
[[redirects]]
  from = "/api/*"
  to = "http://michelleandkeaton.com/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "http://michelleandkeaton.com/:splat"
  status = 301
  force = true
