# Redirect rules for michelleandkeaton.com
[[redirects]]
  from = "/api/*"
  to = "https://michelleandkeaton.com/api/:splat"
  status = 200

[[headers]]
  # Define which paths this specific [[headers]] block will cover.
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"

[build]
command = "npm run build && npm prisma generate"
publish = "dist"
functions = "functions"

[build.environment]
PRISMA_CLIENT_PATH = "./node_modules/.prisma/client"
