# Redirect rules for michelleandkeaton.com
[[redirects]]
  from = "/api/*"
  to = "https://michelleandkeaton.com/api/:splat"
  status = 200

[[headers]]
  # Define which paths this specific [[headers]] block will cover.
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"
